volumes:
  pgData:

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://127.0.0.1:8080/api/
    ports:
      - "3000:80"

  swagger:
    image: swaggerapi/swagger-ui:v5.17.14
    environment:
      - SWAGGER_JSON=/openapi.yaml
    volumes:
      - ./docs/openapi.yaml:/openapi.yaml:ro
    ports:
      - "8081:8080"

  postgres:
    image: postgres:16.4-alpine3.20
    environment:
      - POSTGRES_USER=student
      - POSTGRES_PASSWORD=student666
      - POSTGRES_DB=fitness
    volumes:
      - pgData:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U student -d fitness"]
      interval: 10s
      timeout: 3s
      retries: 3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=student
      - DB_PASSWORD=student666
      - DB_DATABASE=fitness
      - JWT_SECRET=1234
      - JWT_EXPIRES_DAY=30d
      
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "node -e \"fetch('http://localhost:8080/healthcheck').then(r => process.exit(r.ok ? 0 : 1)).catch(() => process.exit(1))\""]
      interval: 10s
      timeout: 3s
      retries: 5